// In-page summary modal (used on the home/feed surface). Manages a single
// modal at a time, body scroll-lock, and Escape / outside-click dismissal.

import { escapeHtml, formatSummary } from "./markdown.js";

const MODAL_ID = "yt-sum-summary-modal";
let escapeHandler = null;
// Each open gets a token; a late response only renders if its token is still
// the active one. Stops a slow request for video A from overwriting the modal
// the user has since opened for video B.
let activeToken = 0;

function lockScroll() {
	const scrollY = window.scrollY;
	document.body.classList.add("yt-sum-modal-open");
	document.body.style.top = `-${scrollY}px`;
	document.body.dataset.ytSumScrollY = String(scrollY);
}

function unlockScroll() {
	document.body.classList.remove("yt-sum-modal-open");
	const y = parseInt(document.body.dataset.ytSumScrollY || "0", 10);
	document.body.style.top = "";
	delete document.body.dataset.ytSumScrollY;
	window.scrollTo(0, y);
}

export function closeModal() {
	const modal = document.getElementById(MODAL_ID);
	if (!modal) return;
	if (escapeHandler) {
		document.removeEventListener("keydown", escapeHandler);
		escapeHandler = null;
	}
	unlockScroll();
	modal.remove();
}

function bodyHtml(inner) {
	return `
    <div class="yt-sum-modal-content">
      <div class="yt-sum-modal-header">
        <h3>${escapeHtml(currentTitle)}</h3>
        <button class="yt-sum-close-btn" aria-label="Close">×</button>
      </div>
      <div class="yt-sum-modal-body">${inner}</div>
    </div>`;
}

let currentTitle = "";

const LOADING_INNER = `
  <div class="yt-sum-loading-container">
    <div class="yt-sum-streaming-loader">
      <span class="yt-sum-bounce-dot"></span>
      <span class="yt-sum-bounce-dot"></span>
      <span class="yt-sum-bounce-dot"></span>
    </div>
    <p class="yt-sum-loading-text">Reading the transcript and summarizing…</p>
  </div>`;

/** Open (or replace) the modal in a loading state. Returns a token to pass to
 * showSummary/showError so a stale response can't overwrite a newer modal. */
export function openLoadingModal(title, { darkMode = false } = {}) {
	closeModal();
	activeToken += 1;
	currentTitle = title || "Summary";
	const modal = document.createElement("div");
	modal.id = MODAL_ID;
	modal.className = darkMode ? "yt-sum-modal dark-mode" : "yt-sum-modal";
	modal.innerHTML = bodyHtml(LOADING_INNER);
	document.body.appendChild(modal);
	lockScroll();

	modal.querySelector(".yt-sum-close-btn").addEventListener("click", closeModal);
	modal.addEventListener("click", (e) => {
		if (e.target === modal) closeModal();
	});
	escapeHandler = (e) => {
		if (e.key === "Escape") closeModal();
	};
	document.addEventListener("keydown", escapeHandler);
	return activeToken;
}

function setBody(html, token) {
	if (token != null && token !== activeToken) return; // stale response
	const modal = document.getElementById(MODAL_ID);
	if (!modal) return;
	const body = modal.querySelector(".yt-sum-modal-body");
	if (body) body.innerHTML = html;
}

/** Update the modal body with partial streaming text (no source note yet, cursor shown). */
export function showStreamingText(text, token) {
	if (token != null && token !== activeToken) return;
	const modal = document.getElementById(MODAL_ID);
	if (!modal) return;
	const body = modal.querySelector(".yt-sum-modal-body");
	if (!body) return;
	body.innerHTML =
		formatSummary(text) + '<span class="yt-sum-cursor" aria-hidden="true">▋</span>';
}

/** Render the finished summary (markdown → safe HTML), with a source note. */
export function showSummary(text, { mode, token } = {}) {
	const note =
		mode === "video"
			? '<p class="yt-sum-source-note">Captions were unavailable, so this was generated by Gemini watching the video.</p>'
			: "";
	setBody(note + formatSummary(text), token);
}

/** Render an error message inside the modal. */
export function showError(message, token) {
	setBody(`<div class="yt-sum-error">${escapeHtml(message)}</div>`, token);
}
